

// get list
GET http://localhost:4000/v1/posts
Accept: application/json

###



# new Post
POST http://localhost:4000/v1/posts
Content-Type: application/json

{
"title": "test title1",
  "body": "test body1",
  "tags": ["test1", "test2"]
}

###


# find by id
GET http://localhost:4000/v1/posts/5f0c362e72706e1aa76d2b36
Accept: application/json

###

### modify by id
PUT http://localhost:4000/v1/posts/5f0d33f2bd0e83a06095dceb
Content-Type: application/json

{
  "title": "Hello baby",
  "body": "modify body",
  "tags": ["aa", "bb", "ccc"]
}

###


DELETE http://localhost:4000/v1/posts/5f0d326f594d9b9e62b9951c
Content-Type: application/json

{ }

###
